argocd staging:
  variables:
    S_TG_BOT_TOKEN: 7368958284:AAGvu8h2UogGfYATn6IP_YJuI-zGam6VstI
include:
  - remote: https://devops-pipeline-manager-production.trendsurfers.ru/manifest.yml?sources=/ci/global/stages&.yml
  - remote: https://devops-pipeline-manager-production.trendsurfers.ru/manifest.yml?sources=/ci/jobs/build/kaniko&.yml
  - remote: https://devops-pipeline-manager-production.trendsurfers.ru/manifest.yml?sources=/ci/jobs/deploy/argocd-staging&.yml
  - remote: https://devops-pipeline-manager-production.trendsurfers.ru/manifest.yml?sources=/ci/jobs/utils/with-submodules&.yml
  - remote: https://devops-pipeline-manager-production.trendsurfers.ru/manifest.yml?sources=/ci/workflow/review-on-mr&.yml
variables:
  DEPLOYMENT_LOAD_ENV_SECRETS: token
  DEPLOY_FROM: .k8s
  HTTP_ENABLED: 'true'
  HTTP_PORT: '8000'
  HTTP_SUBDOMAIN_ON: .trendsurfers.ru
  MAINTAINERS: vapvapapvpva@yandex.ru
  POSTGRES_ENABLED: 'true'