version: "3"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: "redis-server --save 20 1 --loglevel warning"

  app:
    build: .
    env_file:
      - ".env"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  redis_data: